cargo-features = ["edition2024"]

[package]
name = "program"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-program = "2.2.0"
borsh = "1.4.0"
borsh-derive = "1.4.0"
solana-sdk-ids = "2.2.1"

[lib]
crate-type = ["lib", "cdylib"]
